FeatureSetCreator and SimulationGame
se-research-studies/simulation-model-matching pull request #1
Opened 2016-11-18 08:28 UTC by SebastianMelinat

2016-11-18 19:16 UTC, chrberger approved these changes

2016-11-18 19:17 UTC, chrberger requested changes
@SebastianMelinat There are still some conflicts (cf. above); may I ask you to have a look and try to fix them? Thanks.

2016-11-21 08:30 UTC, merged

2016-11-21 08:31 UTC, SebastianMelinat commented
I rebased feature-extractor onto the master branch, the merge conflicts should be solved.

2016-11-21 11:13 UTC, SebastianMelinat commented
I just realized that I opened the pull request in the wrong direction...